START TRANSACTION;
UPDATE frameworks
SET framework = 'VUE.JS'
WHERE framework_id = 3;
DELETE
FROM frameworks;
INSERT INTO frameworks
VALUES (0, "Spring", 5, 2);
ROLLBACK;
COMMIT;

/* NORMALMENTE SE USA CON EL LENGUAJE DE BACKEND PARA QUE POR MEDIO DE EXPECIONES SE DECIDA SI EJECUTAR EL ROLLBACK O EL COMMIT */